### ISSUE TITLE
Always show block cursor

### ISSUE THREAD

**Issue by kahhor** [netpro2k/SublimeBlockCursor#8] opened 2012-04-27 15:14 UTC
Hello,

I don't know if this is a bug or this is the way how it suppose to work. But for me cursor become block only if I switch from one tab to another. Is there any way to have my cursor always as a block, even when I'm on the same page

Thanks,

**Comment by netpro2k** [comment] 2012-05-18 21:01
This sounds like a duplicate of issue #1

**Closed as completed by netpro2k** 2012-05-18 21:01 UTC
